run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck      # Check for unchecked errors (important!)
    - govet         # Reports suspicious constructs
    - staticcheck   # Static analysis checks
    - unused        # Check for unused code
    - ineffassign   # Detect ineffectual assignments

linters-settings:
  errcheck:
    check-blank: false  # Allow _ =
    check-type-assertions: false

  govet:
    enable:
      - shadow
    disable:
      - fieldalignment

issues:
  exclude-use-default: true  # Use default exclusions
  max-issues-per-linter: 50
  max-same-issues: 10

  exclude-rules:
    # Exclude linters from tests
    - path: _test\.go
      linters:
        - errcheck
        - staticcheck

    # Allow shadowing in specific cases
    - linters:
        - govet
      text: "shadow"
